Repository TechnoBlogger14o3/HackerRank-Interview-Preparation-Kit-Solutions, pull requests merged in 2020-10, with the labels that each got.

#3 Added solutions for Warmup challenges in C
  01. Warm-Up-Challenges/Counting-Valleys.c
  01. Warm-Up-Challenges/Jumping-on-the-Clouds.c
  01. Warm-Up-Challenges/Repeated-String.c
  01. Warm-Up-Challenges/Sales-by-Match.c
Labels: hacktoberfest-accepted, hactoberfest

#4 Add files via upload
  14. Miscellaneous/4. Maximum Xor.java
Labels: hacktoberfest, hacktoberfest-accepted, help wanted

#5 Added Topological_Sorting in C++ Language
  04. Sorting/Topological_Sorting.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#7 Implementation of Stack using Arrays
  09. Stacks and Queues/Implement Stack using array.java
Labels: hacktoberfest, hacktoberfest-accepted

#6 Created Bubble Sort code in Java
  04. Sorting/BubbleSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#8 Add Harshitha4444 as contributor
  01. Warm-Up-Challenges/Counting valley.c#
Labels: hacktoberfest, hacktoberfest-accepted

#9 Add Harshitha4444 as contributor
  01. Warm-Up-Challenges/2d array.C++
Labels: hacktoberfest, hacktoberfest-accepted

#10 Add Harshitha4444 as contributor
  01. Warm-Up-Challenges/Solutions in c
Labels: hacktoberfest, hacktoberfest-accepted

#11 c and c++ solution added
  01. Warm-Up-Challenges/Counting Valleys.cpp
  01. Warm-Up-Challenges/Jumping on the Clouds.cpp
  01. Warm-Up-Challenges/Repeated String.cpp
  01. Warm-Up-Challenges/Sock Merchant.c
  02. Arrays/2D Array - DS.cpp
  02. Arrays/Array Manipulation.cpp
  02. Arrays/Left Rotation.cpp
  02. Arrays/Minimum Swaps 2.cpp
  02. Arrays/New Year Chaos.c
  03. Dictionaries and Hashmaps/.DS_Store
  03. Dictionaries and Hashmaps/Count Triplets.cpp
  03. Dictionaries and Hashmaps/Frequency Queries.cpp
  03. Dictionaries and Hashmaps/Ransom Note.cpp
  03. Dictionaries and Hashmaps/Sherlock and Anagrams.cpp
  03. Dictionaries and Hashmaps/Two Strings.cpp
  04. Sorting/.DS_Store
  04. Sorting/Bubble Sort.cpp
  04. Sorting/Comparator.cpp
  04. Sorting/Mark and Toys.cpp
  04. Sorting/Merge Sort; Counting Inversions.cpp
  05. Strings Manipulation/.DS_Store
  05. Strings Manipulation/Alternating Characters.cpp
  05. Strings Manipulation/Common Child.cpp
  05. Strings Manipulation/Making Anagrams.cpp
  05. Strings Manipulation/Sherlock and the Valid String.cpp
  06. Greedy Algorithms/.DS_Store
  06. Greedy Algorithms/Greedy Florist.cpp
  06. Greedy Algorithms/Luck Balance.cpp
  06. Greedy Algorithms/Minimum Absolute Difference in an Array.cpp
  09. Stacks and Queues/Balanced Brackets.cpp
  11. Trees/Height of a Binary Tree.cpp
  12. Linked Lists/Detect a Cycle.cpp
  12. Linked Lists/Find Merge Point of Two Lists.cpp
  12. Linked Lists/Insert a node at a specific position in a linked list.cpp
  12. Linked Lists/Inserting a Node Into a Sorted Doubly Linked List.cpp
  12. Linked Lists/Reverse a doubly linked list.cpp
  13. Recursion and Backtracking/.DS_Store
  13. Recursion and Backtracking/Davis' Staircase.cpp
  13. Recursion and Backtracking/Fibonacci Numbers.cpp
  13. Recursion and Backtracking/Recursive Digit Sum.cpp
  14. Miscellaneous/.DS_Store
  14. Miscellaneous/Flipping bits.cpp
  14. Miscellaneous/Time Complexity Primality.cpp
Labels: hacktoberfest, hacktoberfest-accepted
